(function() {
   document.data = {
      "AFI List": [
         "Citizen Kane",
         "The Godfather",
         "Casablanca",
         "Raging Bull",
         "Singin' in the Rain",
         "Gone with the Wind (film)",
         "Lawrence of Arabia (film)",
         "Schindler's List",
         "Vertigo",
         "The Wizard of Oz (1939 film)",
         "City Lights",
         "The Searchers",
         "Star Wars",
         "Psycho (1960 film)",
         "2001: A Space Odyssey",
         "Sunset Boulevard",
         "The Graduate",
         "The General (1926 film)",
         "On the Waterfront",
         "It's a Wonderful Life",
         "Chinatown (1974 film)",
         "Some Like It Hot",
         "The Grapes of Wrath",
         "E.T. the Extra-Terrestrial",
         "To Kill a Mockingbird",
         "Mr. Smith Goes to Washington",
         "High Noon",
         "All About Eve",
         "Double Indemnity",
         "Apocalypse Now",
         "The Maltese Falcon (1941 film)",
         "The Godfather Part II",
         "One Flew Over the Cuckoo's Nest",
         "Snow White and the Seven Dwarfs (1937 film)",
         "Annie Hall",
         "The Bridge on the River Kwai",
         "The Best Years of Our Lives",
         "The Treasure of the Sierra Madre",
         "Dr. Strangelove",
         "The Sound of Music",
         "King Kong (1933 film)",
         "Bonnie and Clyde",
         "Midnight Cowboy",
         "The Philadelphia Story",
         "Shane",
         "It Happened One Night",
         "A Streetcar Named Desire (1951 film)",
         "Rear Window",
         "Intolerance",
         "The Lord of the Rings: The Fellowship of the Ring",
         "West Side Story (1961 film)",
         "Taxi Driver",
         "The Deer Hunter",
         "MASH",
         "North by Northwest",
         "Jaws",
         "Rocky",
         "The Gold Rush",
         "Nashville",
         "Duck Soup (1933 film)",
         "Sullivan's Travels",
         "American Graffiti",
         "Cabaret (1972 film)",
         "Network (1976 film)",
         "The African Queen",
         "Raiders of the Lost Ark",
         "Who's Afraid of Virginia Woolf?",
         "Unforgiven",
         "Tootsie",
         "A Clockwork Orange",
         "Saving Private Ryan",
         "The Shawshank Redemption",
         "Butch Cassidy and the Sundance Kid",
         "The Silence of the Lambs",
         "In the Heat of the Night",
         "Forrest Gump",
         "All the President's Men",
         "Modern Times",
         "The Wild Bunch",
         "The Apartment",
         "Spartacus",
         "Sunrise: A Song of Two Humans",
         "Titanic (1997 film)",
         "Easy Rider",
         "A Night at the Opera",
         "Platoon",
         "12 Angry Men (1957 film)",
         "Bringing Up Baby",
         "The Sixth Sense",
         "Swing Time",
         "Sophie's Choice",
         "Goodfellas",
         "The French Connection",
         "Pulp Fiction",
         "The Last Picture Show",
         "Do the Right Thing",
         "Blade Runner",
         "Yankee Doodle Dandy",
         "Toy Story",
         "Ben-Hur (1959 film)"
      ]
   }
})();
